name: Lint, Format, and Deploy

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint and Format
        run: |
          npm run lint:fix
          npm run format
          
          git diff --exit-code || (git add . && git commit -m "Lint and format changes" && git push origin HEAD:$GITHUB_REF)
        env:
          GITHUB_REF: ${{ github.head_ref }}
          CI: true
        continue-on-error: true